# Initalize
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "appveyor"

# Test settings
test: on

# Branches whitelist
branches:
  only:
    - master
    - develop